# Generated by Django 3.2.12 on 2022-03-18 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_extend_tag_support'),
        ('dcim', '0144_fix_cable_abs_length'),
        ('ipam', '0053_asn_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhrpgroup',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fhrpgroup', to='dcim.site'),
        ),
        migrations.AddField(
            model_name='fhrpgroup',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fhrpgroup', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='fhrpgroup',
            name='vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fhrpgroup', to='ipam.vlan'),
        ),
        migrations.AddField(
            model_name='fhrpgroup',
            name='vlan_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fhrpgroup', to='ipam.vlangroup'),
        ),
    ]
